NAME    = opt-guile
VERSION = 2.0.9
RELEASE = 0
RPM.EXTRAS         = AutoReq:No

SRC_SUBDIR	= guile

GUILE_NAME	= guile
GUILE_VERSION	= $(VERSION)
GUILE_SOURCE	= $(GUILE_NAME)-$(GUILE_VERSION).tar.gz

TAR_GZ_PKGS = $(GUILE_SOURCE)
