NAME    = opt-texinfo
VERSION = 5.1
RELEASE = 0
RPM.EXTRAS         = AutoReq:No

SRC_SUBDIR	= texinfo

TEXINFO_NAME	= texinfo
TEXINFO_VERSION	= $(VERSION)
TEXINFO_SOURCE	= $(TEXINFO_NAME)-$(TEXINFO_VERSION).tar.gz

TAR_GZ_PKGS	= $(TEXINFO_SOURCE)

