NAME    = opt-libffi
VERSION = 3.0.13
RELEASE = 1
RPM.EXTRAS         = AutoReq:No

SRC_SUBDIR	= libffi

LIBFFI_NAME	= libffi
LIBFFI_VERSION	= $(VERSION)
LIBFFI_SOURCE	= $(LIBFFI_NAME)-$(LIBFFI_VERSION).tar.gz

TAR_GZ_PKGS	= $(LIBFFI_SOURCE)
