#%Module1.0
module-whatis "GNU tools"
module-whatis "Version: VERSION"
module-whatis "Description: GNU tools"
proc ModulesHelp { } {
	puts stderr "\tThis module file adds newer versions of GNU utilities"
	puts stderr "\tthan are available from the current CentOS release."
	puts stderr "\t"
	puts stderr "\tDepending on the particular cluster, it may also have paths"
	puts stderr "\tto a more recent GNU compiler release as well."
}

setenv GNUTOOLSHOME /opt/gnu
prepend-path PATH /opt/gnu/bin
prepend-path LD_LIBRARY_PATH /opt/gnu/lib:/opt/gnu/lib64
