NAME    = opt-autoconf
VERSION = 2.69
RELEASE = 0
RPM.EXTRAS         = AutoReq:No

SRC_SUBDIR = autoconf

AUTOCONF_NAME = autoconf
AUTOCONF_VERSION = 2.69
AUTOCONF_SOURCE = $(AUTOCONF_NAME)-$(AUTOCONF_VERSION).tar.gz

TAR_GZ_PKGS = $(AUTOCONF_SOURCE)

