NAME    = opt-automake
VERSION = 1.14
RELEASE = 7

SRC_SUBDIR = automake

AUTOMAKE_NAME = automake
AUTOMAKE_VERSION = $(VERSION)
AUTOMAKE_SOURCE = $(AUTOMAKE_NAME)-$(AUTOMAKE_VERSION).tar.gz

TAR_GZ_PKGS = $(AUTOMAKE_SOURCE)
