NAME    	= opt-binutils
VERSION 	= 2.22
RELEASE 	= 1
RPM.EXTRAS         = AutoReq:No

SRC_SUBDIR	= binutils

BINUTILS_NAME	= binutils
BINUTILS_VERSION	= $(VERSION)
BINUTILS_SOURCE	= $(BINUTILS_NAME)-$(BINUTILS_VERSION).tar.gz

TAR_GZ_PKGS = $(BINUTILS_SOURCE)
