NAME    = opt-libunistring
VERSION = 0.9.3
RELEASE = 7

SRC_SUBDIR	= libunistring

LIBUNISTRING_NAME	= libunistring
LIBUNISTRING_VERSION	= $(VERSION)
LIBUNISTRING_SOURCE	= $(LIBUNISTRING_NAME)-$(LIBUNISTRING_VERSION).tar.gz

TAR_GZ_PKGS	= $(LIBUNISTRING_SOURCE)

