NAME    = opt-libtool
VERSION = 2.4.2
RELEASE = 1
RPM.EXTRAS         = AutoReq:No

SRC_SUBDIR	= libtool

LIBTOOL_NAME	= libtool
LIBTOOL_VERSION	= $(VERSION)
LIBTOOL_SOURCE	= $(LIBTOOL_NAME)-$(LIBTOOL_VERSION).tar.gz

TAR_GZ_PKGS	= $(LIBTOOL_SOURCE)

