NAME    = opt-bdwgc
VERSION = 7.2alpha7
RELEASE = 1
RPM.EXTRAS         = AutoReq:No

SRC_SUBDIR = bdwgc

BDWGC_NAME = bdwgc
BDWGC_VERSION = $(VERSION)
BDWGC_SOURCE = $(BDWGC_NAME)-$(BDWGC_VERSION).tar.gz

TAR_GZ_PKGS = $(BDWGC_SOURCE)
