#%Module1.0
module-whatis "GNU base"
module-whatis "Version: VERSION"
module-whatis "Description: GNU base"
proc ModulesHelp { } {
        puts stderr "\tThis module file adds newer versions of GNU utilities"
        puts stderr "\tthen are available from the current CentOS release."
        puts stderr "\t"
        puts stderr "\tIt excludes paths to a more recent GNU compiler release "
        puts stderr "\tthen is available from the current CentOS release."
}

setenv GNUTOOLSHOME /opt/gnu
prepend-path PATH /opt/gnu/bin
prepend-path LD_LIBRARY_PATH /opt/gnu/lib:/opt/gnu/lib64
